### ISSUE TITLE
syntax-check[missing-file] false postive when using import_playbook in a play

### ISSUE THREAD

**Issue by bivanbi** [4ch1m/intellij-ansible-lint#12]
Steps to reproduce:
1. Install PyCharm PE 2023.2 + Ansible Lint plugin 1.5.6
2. Open a playbook to edit
3. Import another playbook with the 'ansible.builtin.import_playbook' directive
4. Observe error message:
  ```
  Unable to retrieve file contents | Could not find or access '/tmp/10054813971726606045/plays/system/users.yml' on the Ansible Controller. | Rule: syntax-check[missing-file] <core,unskippable>
  ```

Running `ansible-lint` on the command line works just fine.

Checked with inotifywait to see what is happeing in /tmp, and it seems like the only playbook copied from 'plays' directory is the one being edited in jetbrains product. This explains why ansible lint outputs this error.

**Comment by 4ch1m** [comment]
The plugin needs to "replicate" the surrounding structure of the file being linted.
Otherwise you wouldn't get up-to-date results that are in sync with the editor.
And that's why you'll find several files/symlinks in `/tmp`.

For details, please check:

- https://github.com/4ch1m/intellij-ansible-lint/blob/de8f3975f983c128d3e8d1ccc86ea9c4e23fc507/src/main/kotlin/de/achimonline/ansible_lint/annotator/AnsibleLintAnnotator.kt#L64-L80

- https://github.com/4ch1m/intellij-ansible-lint/blob/de8f3975f983c128d3e8d1ccc86ea9c4e23fc507/src/main/kotlin/de/achimonline/ansible_lint/common/AnsibleLintTempEnv.kt#L1-L102

The `plays/system`-subfolder (which is mentioned in your report above) is not a "standard" Ansible folder as per: https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout

In that example, additional/imported playbooks are placed in the root.

However, the plugin currently also doesn't handle those files either.

What happens, if you use the **absolute** path in your import-statement?

e.g.
```
- name: Include a play
  ansible.builtin.import_playbook: /full/path/to/playbook.yaml
```

(Either way... I don't think that would be a valid workaround/solution. :smile:)

I'll try to figure out how to reference additional playbooks in the root-folder in the meantime.

**Comment by bivanbi** [comment]
Thank you for the swift response!

I believe the issue happens if I follow the mentioned directory layout.
```
bivanbi@eenovo:~/src/ansible$ ls test*
test2.yml  test_play.yml
bivanbi@eenovo:~/src/ansible$ cat test_play.yml 
---
- name: Import playbook
  ansible.builtin.import_playbook: test2.yml
```
And the error: 
```
Unable to retrieve file contents | Could not find or access '/tmp/13281396532265179964/test2.yml' on the Ansible Controller. | Rule: syntax-check[missing-file] <core,unskippable>
```

Seems like importing playbooks from collections are fine, so it might not worth the effort. (I am already transforming my plays / roles)

**Comment by 4ch1m** [comment]
The plugin now will create symlinks to _all_ YAML-resources in the project (d02750b44db11b9f1e85fa70d468abc651c89353).
Which should be a safe and effective approach.

This should also resolve your issue.

Thanks a lot for reporting!
