### ISSUE TITLE
Overview should show that ansible-lint is not supported on windows

### ISSUE THREAD

**Issue by andreasmuelhaupt** [4ch1m/intellij-ansible-lint#18]
Hi @4ch1m,
first of all thank you for providing an open source plug-in for the intellij and ansible using community.
As I have recently started to use ansible and wanted to use it in my favourite IDE I thought that a linter would be nice, which brought me to your project.

As Ansible Lint relies on python module ansible-lint, which [can not be used on windows](https://ansible.readthedocs.io/projects/lint/installing/#installing), it should be listed as requirement or made otherwise visible in the marketplace, so that a user knows that an installation (and re-start, and trial-error configuration, and uninstall and re-start again) would be pointless efforts.

#edit: removed rudeness

**Comment by 4ch1m** [comment]
> As Ansible Lint relies on python module ansible-lint, which can not be used on windows

That is not quite correct.
There are people successfully running the plugin on Windows using WSL (Windows Subsystem for Linux).
However, I can't give any support on that since I don't use Windows myself.

Besides, it should be pretty obvious that the plugin is utilizing the existing `ansible-lint` installation on your system.
The description and README (see `Requirements`) also makes this pretty clear.

**Comment by 4ch1m** [comment]
@andreasmuelhaupt FYI: The plugin now officially supports WSL. You might want to try it out.
