### ISSUE TITLE
Continuous High CPU Usage and working randomly

### ISSUE THREAD

**Issue by mickaelperrin** [4ch1m/intellij-ansible-lint#24]
Hi,

I try to get yout plugin working and I experience some issues:
- activity monitor indicates a CPU usage of 100% related to Plugin Ansible Lint: de.achimonline.ansible_lint.common
- errors reported by the lint are showed very infrequently. They disappears after an edit and it takes a very long time to be redisplayed. Some times they simply don't appear anymore.

My setup:
- MacOS Sonoma 14.6.1 (23G93)
- PhpStorm 2024.2.3
- Plugin version 1.9.0
- Every market place plugins disabled
- Ansible lint version: ansible-lint 24.9.2 using ansible-core:2.14.17 ansible-compat:24.9.1 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.12
- 8192Mb of Heap Size

My lint script:
```
#!/bin/bash
source ~/.virtualenvs/xxxx/bin/activate
ansible-lint "$@"
```

I also did some tries with ansible-lint directly installed with brew without success and did an invalidate caches also.

Here is a thread dump: [threadDump-20241106-191045.txt](https://github.com/user-attachments/files/17651275/threadDump-20241106-191045.txt)

I don't know if you need something else to investigate.

Thanks,

**Comment by 4ch1m** [comment]
Hi there,

Thanks for your feedback.

> Hi,
> 
> I try to get yout plugin working and I experience some issues:
> 
>     * activity monitor indicates a CPU usage of 100% related to Plugin Ansible Lint: de.achimonline.ansible_lint.common

Short bursts of high CPU usage can occur; depending on your system/hardware.
Running `ansible-lint` outside of the plugin also sometimes consumes around ~40-50% of my CPU.

>     * errors reported by the lint are showed very infrequently. They disappears after an edit and it takes a very long time to be redisplayed. Some times they simply don't appear anymore.

That's to be expected, since the plugin invokes `ansible-lint` in the background whenever there's a change in your editor(content).
Otherwise you wouldn't get instant feedback in your IDE.

When you stop editing and let the linter finish, then you should always see the current results.
(How long linting takes, is - of course - dependant on your system/hardware.)

> ...
> Here is a thread dump: [threadDump-20241106-191045.txt](https://github.com/user-attachments/files/17651275/threadDump-20241106-191045.txt)
> 
> I don't know if you need something else to investigate.

Not sure if there's useful information in that for me.

Please feel free to provide suggestions (or even pull-requests) on how to improve the plugin's code. I'll gladly review it.

Thanks!
