### ISSUE TITLE
Unable to use on Windows

### ISSUE THREAD

**Issue by 0x464e** [4ch1m/intellij-ansible-lint#8]
So yeah, I tried everything I could think of, using a wsl path to the native binary, using a bash script like in the README through wsl, having the README's bash script equivalent on Windows side with powershell, compiling the aforementioned powershell script to a executable,..  
And nothing works.  
Long story short, don't try to use on Windows, or maybe there's some trick which I'm missing.

**Comment by 4ch1m** [comment]
So yeah, I don't use Windows / WSL.
The plugin has a dedicated `TEST` button in the settings dialog; which can be used to find out if your Powershell script actually works as expected when being invoked from IntelliJ.
Longer story short, this plugin is open source.
Maybe you can contribute and analyze why "nothing works" (for you).

Closing this issue; since it is not primarily a problem of the plugin.

**Comment by david-pili** [comment]
try pipx instead if you still have issues
## Pipx

Pipx can be used as an alternative to manually configuring a venv. It has the advantage of automatically adding the installed binaries to your path and allows specifying the ansible verion ansible-lint uses

* Install [Pipx](https://pipx.pypa.io/stable/)

* Install ansible with pipx (change 6.7.0 to your required version, or remove it to install the latest)
  ```
  pipx install --include-deps ansible==6.7.0
  ```

* Inject ansible-lint into the pipx ansible venv 
  ```
  pipx inject --include-deps ansible ansible-lint
  ```

`ansible` and `ansible-lint` should now be availible in your path

**Comment by 4ch1m** [comment]
FYI: The plugin now officially supports WSL. You might want to try it out.
